[package]
name = "magi"
version = "0.0.1"
authors = ["Michael Volling"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.16.0"
strum_macros = "0.16.0"